### PR TITLE
Fix gradient zone

### PR DESCRIPTION
**Pull request by Kuuuube**
image

This makes the gradient apply only to the text instead of extending to (probably) the entire page. The values for the gradient can be changed properly.

### CODE REVIEW

**Comment by jamesmaa** [comment]
> This makes the gradient apply only to the text instead of extending to (probably) the entire page. The values for the gradient can be changed properly.

How would that happen originally? The css rule was already scoped to the `homepage-title` id

**Comment by Kuuuube** [comment]
Well not actually the whole page it looks like but this whole range:
image

That's the area covered by `homepage-title`.

**Comment by jamesmaa** [comment]
- I feel like the `p` should be `homepage-title-wrapper` and the span `homepage-title`.
- Could we make the `p` a div?
- Somehow the bold is no longer there and "Yomitan" looks emaciated, could you fix that?
- Still unsure about this gradient matching the icon/logo. I don't think it's aesthetically necessary to match. Right now the gradient seems a bit too strong (high contrast) and clashes with the rest of the theme of the website

**Comment by Kuuuube** [comment]
>I feel like the p should be homepage-title-wrapper and the span homepage-title.

Switched

>Could we make the p a div?

Sure

>Somehow the bold is no longer there and "Yomitan" looks emaciated, could you fix that?

I think this is some difference in my browser or fonts. Even the currently deployed yomitan wiki without these changes doesnt appear bold for me.

>Still unsure about this gradient matching the icon/logo. I don't think it's aesthetically necessary to match. Right now the gradient seems a bit too strong (high contrast) and clashes with the rest of the theme of the website

I'm fine to change it to whatever. But it does need to actually apply to the text correctly whichever colors we choose.

**Comment by Kuuuube** [comment]
Fixed the bold. Now looks like this on both chromium and firefox:
image

**Review by jamesmaa — APPROVED** [review]

**Pull request merged**
